[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "9kKLuKpHXLHLHDGzs12Se7XV8oAgargMjhr8Ew8A9xPx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arjein/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
